### ISSUE TITLE
Scan commit body

### ISSUE THREAD

**Issue by martinvysnovsky** [CircleCI-Public/jira-orb#31]
We are adding a Jira ticket number to the body of the commit message. In version `1.3.1`, there is the `scan_commit_body` option. After updating to version 2, there is no such option. Can you please include it in v2 as well? Or maybe scan the commit body by default.

**Comment by martinvysnovsky** [comment]
I have already created a pull request for it :)
https://github.com/CircleCI-Public/jira-orb/pull/32

**Comment by KyleTryon** [comment]
Merged, thank you!
